In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
%matplotlib inline
from sklearn import datasets
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB

In [11]:
dataset=datasets.load_iris()
model=GaussianNB()

In [12]:
model.fit(dataset.data,dataset.target)

GaussianNB(priors=None, var_smoothing=1e-09)

In [13]:
print(model)

GaussianNB(priors=None, var_smoothing=1e-09)


In [14]:
expected=dataset.target
predicted=model.predict(dataset.data)

In [15]:
print(metrics.classification_report(expected,predicted))
print(metrics.confusion_matrix(expected,predicted))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       0.94      0.94      0.94        50
           2       0.94      0.94      0.94        50

    accuracy                           0.96       150
   macro avg       0.96      0.96      0.96       150
weighted avg       0.96      0.96      0.96       150

[[50  0  0]
 [ 0 47  3]
 [ 0  3 47]]
